from sql_functions import *

db = create_db("database")
cur = get_cur(db)

try:

    book_list = [
        (1, "Fundamentals of Wavelets", "Goswami, Jaideva", "yes"),
        (2, "Data Smart", "Foreman, John", "yes"),
        (3, "God Created the Integers", "Hawking, Stephen", "yes"),
        (4, "Superfreakonomics", "Dubner, Stephen", "yes"),
        (5, "Orientalism", "Said, Edward", "yes"),
        (6, "Nature of Statistical Learning Theory ", "Vapnik, Vladimir", "yes"),
        (7, "Integration of the Indian States", "Menon, V P", "yes"),
        (8, "Drunkard's Walk ", "Mlodinow, Leonard", "yes"),
        (9, "Image Processing & Mathematical Morphology", "Shih, Frank", "yes"),
        (10, "How to Think Like Sherlock Holmes", "Konnikova, Maria", "yes"),
        (11, "Data Scientists at Work", "Sebastian Gutierrez", "yes"),
        (12, "Slaughterhouse Five", "Vonnegut, Kurt", "yes"),
        (13, "Birth of a Theorem", "Villani, Cedric", "yes"),
        (14,"Structure & Interpretation of Computer Programs","Sussman, Gerald","yes",),
        (15, "Age of Wrath ", "Eraly, Abraham", "yes"),
        (16, "Trial ", "Kafka, Frank", "yes"),
        (17, "Statistical Decision Theory'", "Pratt, John", "yes"),
        (18, "Data Mining Handbook", "Nisbet, Robert", "yes"),
        (19, "New Machiavelli ", "Wells, H. G.", "yes"),
        (20, "Physics & Philosophy", "Heisenberg, Werner", "yes"),
        (21, "Making Software", "Oram, Andy", "yes"),
        (22, "Analysis, Vol I", "Tao, Terence", "yes"),
        (23, "Machine Learning for Hackers", "Conway, Drew", "yes"),
        (24, "Signal and the Noise ", "Silver, Nate", "yes"),
        (25, "Python for Data Analysis", "McKinney, Wes", "yes"),
        (26, "Introduction to Algorithms", "Cormen, Thomas", "yes"),
        (27, "Beautiful and the Damned ", "Deb, Siddhartha", "yes"),
        (28, "Outsider ", "Camus, Albert", "yes"),
        (29, "Complete Sherlock Holmes  - Vol I", "Doyle, Arthur Conan", "yes"),
        (30, "Complete Sherlock Holmes  - Vol II", "Doyle, Arthur Conan", "yes"),
        (31, "Wealth of Nations ", "Smith, Adam", "yes"),
        (32, "Pillars of the Earth ", "Follett, Ken", "yes"),
        (33, "Mein Kampf", "Hitler, Adolf", "yes"),
        (34, "Tao of Physics ", "Capra, Fritjof", "yes"),
        (35, "Surely You're Joking Mr Feynman", "Feynman, Richard", "yes"),
        (36, "Farewell to Arms, A", "Hemingway, Ernest", "yes"),
        (37, "Veteran ", "Forsyth, Frederick", "yes"),
        (38, "False Impressions", "Archer, Jeffery", "yes"),
        (39, "Last Lecture ", "Pausch, Randy", "yes"),
        (40, "Return of the Primitive", "Rand, Ayn", "yes"),
        (41, "Jurassic Park", "Crichton, Michael", "yes"),
        (42, "Russian Journal, A", "Steinbeck, John", "yes"),
        (43, "Tales of Mystery and Imagination", "Poe, Edgar Allen", "yes"),
        (44, "Freakonomics", "Dubner, Stephen", "yes"),
        (45, "Hidden Connections ", "Capra, Fritjof", "yes"),
        (46, "Story of Philosophy ", "Durant, Will", "yes"),
        (47, "Asami Asami", "Deshpande, P L", "yes"),
        (48, "Journal of a Novel", "Steinbeck, John", "yes"),
        (49, "Once There Was a War", "Steinbeck, John", "yes"),
        (50, "Moon is Down ", "Steinbeck, John", "yes"),
        (51, "Brethren ", "Grisham, John", "yes"),
        (52, "In a Free State", "Naipaul, V. S.", "yes"),
        (53, "Catch 22", "Heller, Joseph", "yes"),
        (54, "Complete Mastermind ", "BBC", "yes"),
        (55, "Dylan on Dylan", "Dylan, Bob", "yes"),
        (56, "Soft Computing & Intelligent Systems", "Gupta, Madan", "yes"),
        (57, "Textbook of Economic Theory", "Stonier, Alfred", "yes"),
        (58, "Econometric Analysis", "Greene, W. H.", "yes"),
        (59, "Learning OpenCV", "Bradsky, Gary", "yes"),
        (60, "Data Structures Using C & C++", "Tanenbaum, Andrew", "yes"),
        (61, "Computer Vision, A Modern Approach", "Forsyth, David", "yes"),
        (62, "Principles of Communication Systems", "Taub, Schilling", "yes"),
        (63, "Let Us C", "Kanetkar, Yashwant", "yes"),
        (64, "Amulet of Samarkand ", "Stroud, Jonathan", "yes"),
        (65, "Crime and Punishment", "Dostoevsky, Fyodor", "yes"),
        (66, "Angels & Demons", "Brown, Dan", "yes"),
        (67, "Argumentative Indian ", "Sen, Amartya", "yes"),
        (68, "Sea of Poppies", "Ghosh, Amitav", "yes"),
        (69, "Idea of Justice ", "Sen, Amartya", "yes"),
        (70, "Raisin in the Sun, A", "Hansberry, Lorraine", "yes"),
        (71, "All the President's Men", "Woodward, Bob", "yes"),
        (72, "Prisoner of Birth, A", "Archer, Jeffery", "yes"),
        (73, "Scoop!", "Nayar, Kuldip", "yes"),
        (74, "Ahe Manohar Tari", "Deshpande, Sunita", "yes"),
        (75, "Last Mughal ", "Dalrymple, William", "yes"),
        (76, "Social Choice & Welfare, Vol 39 No. 1", "Various", "yes"),
        (77, "Radiowaril Bhashane & Shrutika", "Deshpande, P L", "yes"),
        (78, "Gun Gayin Awadi", "Deshpande, P L", "yes"),
        (79, "Aghal Paghal", "Deshpande, P L", "yes"),
        (80, "Maqta-e-Ghalib", "Garg, Sanjay", "yes"),
        (81, "Manasa", "Kale, V P", "yes"),
        (82, "India from Midnight to Milennium", "Tharoor, Shashi", "yes"),
        (83, "Great Indian Novel ", "Tharoor, Shashi", "yes"),
        (84, "O Jerusalem!", "Lapierre, Dominique", "yes"),
        (85, "City of Joy ", "Lapierre, Dominique", "yes"),
        (86, "Freedom at Midnight", "Lapierre, Dominique", "yes"),
        (87, "Winter of Our Discontent ", "Steinbeck, John", "yes"),
        (88, "On Education", "Russell, Bertrand", "yes"),
        (89, "Free Will", "Harris, Sam", "yes"),
        (90, "Bookless in Baghdad", "Tharoor, Shashi", "yes"),
        (91, "Theory of Everything ", "Hawking, Stephen", "yes"),
        (92, "New Markets & Other Essays", "Drucker, Peter", "yes"),
        (93, "Electric Universe", "Bodanis, David", "yes"),
        (94, "Hunchback of Notre Dame ", "Hugo, Victor", "yes"),
        (95, "Burning Bright", "Steinbeck, John", "yes"),
        (96, "Age of Discontuinity ", "Drucker, Peter", "yes"),
        (97, "Doctor in the Nude", "Gordon, Richard", "yes"),
        (98, "Down and Out in Paris & London", "Orwell, George", "yes"),
        (99, "Identity & Violence", "Sen, Amartya", "yes"),
        (100, "Beyond the Three Seas", "Dalrymple, William", "yes"),
        (101, "Maugham's Collected Short Stories, Vol 3", "Maugham, William S", "yes"),
        (102, "Ashenden of The British Agent", "Maugham, William S", "yes"),
        (103, "Zen & The Art of Motorcycle Maintenance", "Pirsig, Robert", "yes"),
        (104, "Great War for Civilization ", "Fisk, Robert", "yes"),
        (105, "We the Living", "Rand, Ayn", "yes"),
        (106, "Artist and the Mathematician ", "Aczel, Amir", "yes"),
        (107, "History of Western Philosophy", "Russell, Bertrand", "yes"),
        (108, "Rationality & Freedom", "Sen, Amartya", "yes"),
        (109,"Clash of Civilizations","Huntington, Samuel","yes",),
        (110, "Uncommon Wisdom", "Capra, Fritjof", "yes"),
        (111, "One", "Bach, Richard", "yes"),
        (112, "To Sir With Love", "Braithwaite", "yes"),
    ]
    student_list = [
        ("ADR20CS001", "Adil K V"),
        ("ADR20CS002", "Agib Asif"),
        ("ADR20CS003", "Aiswarya S Babu"),
        ("ADR20CS004", "Akshay S"),
        ("ADR20CS005", "Alan Savio"),
        ("ADR20CS006", "Albin J Alex"),
        ("ADR20CS007", "Alen Mathew"),
        ("ADR20CS008", "Alen N"),
        ("ADR20CS009", "Althaf A"),
        ("ADR20CS010", "Alwin Joseph"),
        ("ADR20CS011", "Amogh K T"),
        ("ADR20CS012", "Anandukrishnan U"),
        ("ADR20CS013", "Angel Aniyan"),
        ("ADR20CS014", "Anjana Jayaprakash"),
        ("ADR20CS015", "Arjun S Nair"),
        ("ADR20CS016", "Arunima K"),
        ("ADR20CS017", "Asish S Jacob"),
        ("ADR20CS018", "Austin Vincent"),
        ("ADR20CS019", "Devananda"),
        ("ADR20CS020", "Devanarayanan M P"),
        ("ADR20CS021", "Diya Anna Mathew"),
        ("ADR20CS022", "Faheem P A"),
        ("ADR20CS023", "Febin R"),
        ("ADR20CS024", "Gayathri"),
        ("ADR20CS025", "Gokul Krishna A B"),
        ("ADR20CS026", "Govind P Kumar"),
        ("ADR20CS027", "Imtiyaz Ali"),
        ("ADR20CS028", "Irene Alsa George"),
        ("ADR20CS029", "Jemy Mathew"),
        ("ADR20CS030", "Kashinath S"),
        ("ADR20CS031", "Liny Koshy"),
        ("ADR20CS032", "Meenaskshi B"),
        ("ADR20CS033", "Mohamed Ali"),
        ("ADR20CS034", "Mohammed Fadil P A"),
        ("ADR20CS035", "Muhammed Yaseen"),
        ("ADR20CS036", "Muhammed Afzar S"),
        ("ADR20CS037", "Neha"),
        ("ADR20CS038", "Prijin John"),
        ("ADR20CS039", "Princy Varghese"),
        ("ADR20CS040", "Roshan Shaji"),
    ]

    table_name = "books"
    attributes = (
        "Book_ID integer primary key,Book_name text, Author_name text, Available text"
    )
    create_table(cur, table_name, attributes)
    insert_into_table(cur, table_name, book_list)

    table_name = "students"
    attributes = "KTU_ID text primary key, NAME text"
    create_table(cur, table_name, attributes)
    insert_into_table(cur, table_name, student_list)

    create_table(
        cur,
        "books_rented",
        "Book_ID integer, KTU_ID text, rent_time text, return_time text",
    )
    print("Database and required tables were created sucessfully")
except Exception as e:
    print(e)

finally:
    db.commit()
    db.close()
